version: 2
orbs:
    gcp-gcr: circleci/gcp-gcr@0.6.1
    cloudrun: circleci/gcp-cloud-run@1.0.0

defaults: &defaults
  machine:
  environment:
    - APP_VERSION: $CIRCLE_SHA1

jobs:
  test:
    machine: true
    <<: *defaults
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE:latest .
      - run: docker run -d --rm --name node_app $DOCKER_IMAGE:latest
      - run: docker stop node_app

  publish:
    machine: true
    <<: *defaults
    steps:
      - checkout
      - run: docker build --build-arg APP_VERSION=$CIRCLE_SHA1 -t $DOCKER_IMAGE:$CIRCLE_SHA1 .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push $DOCKER_IMAGE:$CIRCLE_SHA1
  
  deploy:
    machine: true
    <<: *defaults
    steps:
      - gcp-gcr/gcr-auth:
         gcloud-service-key: GOOGLE_CLOUD_KEYS
         google-project-id: GOOGLE_PROJECT_ID
         google-compute-zone: GOOGLE_COMPUTE_ZONE
      - cloudrun/deploy:
         platform: "managed"
         image: "docker.io/$DOCKER_USER/$DOCKER_IMAGE:$CIRCLE_SHA1"
         service-name: "orb-gcp-cloud-run"
         region: $GOOGLE_COMPUTE_ZONE
         unauthenticated: true        


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test:
          context: webApp
      - publish:
          requires:
            - test
          context: webApp
          filters:
            branches:
              only: master
      - deploy:
            requires:
                - publish

